@startuml "WEB_TooLongToRead_2023_UML"

skinparam linetype ortho

set namespaceSeparator .

title Too Long To Read - UML

namespace Controller {

}

namespace Model {
    namespace Wrapper {
        abstract class AbstractWrapper {
            -httpClient: GuzzleHttp\Client
            -baseUri: string
        }

        class Goodreads extends AbstractWrapper {

        }
        class OpenLibrary extends AbstractWrapper {

        }
        class LibraryThing extends AbstractWrapper {
        }
        class Nasa extends AbstractWrapper {
            -httpClient: GuzzleHttp\Client
            -token: string

            +getApod(string date, string startDate, string endDate): GuzzleHttp\Promise\PromiseInterface
        }
    }
}

namespace View {
    class View {
        +render()
    }
}

@enduml