name: Create new release when new semver tag created

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - run: gh release create ${{ github.ref_name }} --generate-notes --latest -t "Too Long To Read ${{ github.ref_name }}" --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}